### ISSUE TITLE
Return types of certain calls are incorrectly marked as f32

### ISSUE THREAD

**Issue by angeld23** [kladd/krpc-client#19]
For example: `CelestialBody_get_Mass` in the SpaceCenter service definition has its return type marked as "FLOAT", but according to the kRPC documentation, it's a double. This is probably why the client is telling me that Kerbin weighs negative 0.000000000021207643 kilograms.

**Comment by kladd** [comment]
Thanks for the report. I've updated the service definitions to the 0.5.4 version in 024ae753. I'll update crates.io after I test a little more.

Here's my output for CelestialBody_get_Mass now.

```
mass is: 52915158343921546000000
```

**Comment by kladd** [comment]
Resolved in v0.6.0, with service definitions from kRPC 0.5.4.
